name: Publish NuGet

on:
  push:
    branches:
      - my-ci

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x

    - name: Add JKorf source
      run: dotnet nuget add source --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/JKorf/index.json"

    - name: Restore
      run: dotnet restore Polymarket.Net/Polymarket.Net.csproj

    - name: Build
      run: dotnet build Polymarket.Net/Polymarket.Net.csproj -c Release --no-restore

    - name: Pack
      run: dotnet pack Polymarket.Net/Polymarket.Net.csproj -c Release --no-build -o ./nupkg

    - name: Push to nuget.org
      run: dotnet nuget push ./nupkg/*.nupkg --source "https://api.nuget.org/v3/index.json" --api-key ${{ secrets.NUGET_API_KEY }} --skip-duplicate